### ISSUE TITLE
Crash upon load

### ISSUE THREAD

**Issue by AvangionQ** [BDWSSBB/StS-Strawberry-Spire#11]
19:42:27.353 INFO core.CardCrawlGame> Zap, 0
19:42:27.359 INFO relics.PrayerBeads> initialized
19:42:27.380 INFO helpers.PotionHelper> MISSING KEY: POTIONHELPER 37: Adrenaline Potion
19:42:27.381 INFO PotionLibrary.PotionHelperGetPotion> Getting custom potion: Adrenaline Potion
19:42:27.382 INFO basemod.BaseMod> publish on potion get
19:42:27.383 INFO helpers.PotionHelper> MISSING KEY: POTIONHELPER 37: infinitespire:BlackPotion
19:42:27.383 INFO PotionLibrary.PotionHelperGetPotion> Getting custom potion: infinitespire:BlackPotion
19:42:27.391 INFO basemod.BaseMod> publish on potion get
19:42:27.393 INFO basemod.BaseMod> publish on potion get
19:42:27.393 INFO helpers.PotionHelper> MISSING KEY: POTIONHELPER 37: infinitespire:BlackPotion
19:42:27.394 INFO PotionLibrary.PotionHelperGetPotion> Getting custom potion: infinitespire:BlackPotion
19:42:27.394 INFO basemod.BaseMod> publish on potion get
19:42:27.395 INFO basemod.BaseMod> publish on potion get
Exception: java.lang.IndexOutOfBoundsException: Index: 104, Size: 104
19:42:27.400 ERROR core.CardCrawlGame> Exception caught
java.lang.IndexOutOfBoundsException: Index: 104, Size: 104
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_144]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_144]
	at StrawberrySpireMod.relics.DirtyLipstick.onLoad(DirtyLipstick.java:65) ~[StrawberrySpire.jar:?]
	at StrawberrySpireMod.relics.DirtyLipstick.onLoad(DirtyLipstick.java:13) ~[StrawberrySpire.jar:?]
	at basemod.abstracts.CustomSavable.onLoadRaw(CustomSavable.java:40) ~[BaseMod.jar:?]
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.LoadPlayerSaves.Postfix(LoadPlayerSaves.java:36) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.loadPlayerSave(CardCrawlGame.java:1283) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:803) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by BDWSSBB** [comment]
Ah geez. I hate these kinds of relics. Thanks for the report. If you have any idea on how to replicate this reliably, please give me some details.
