### ISSUE TITLE
Crash when upgrading cards via event

### ISSUE THREAD

**Issue by AvangionQ** [BDWSSBB/StS-Strawberry-Spire#8]
01:21:54.777 INFO ThMod.ThMod> MarisaModEventPatch : GetEventPatch : PlayerCharacter  : The Necromancer ; retVal event : com.megacrit.cardcrawl.events.exordium.ShiningLight@5e0b5acb
Exception: java.lang.NullPointerException
01:21:58.269 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.actions.common.ApplyPowerAction.<init>(ApplyPowerAction.java:102) ~[?:?]
	at com.megacrit.cardcrawl.actions.common.ApplyPowerAction.<init>(ApplyPowerAction.java:127) ~[?:?]
	at StrawberrySpireMod.relics.ThornyGelberry.onAttacked(ThornyGelberry.java:30) ~[StrawberrySpire.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.damage(AbstractPlayer.java:1654) ~[?:?]
	at com.megacrit.cardcrawl.events.exordium.ShiningLight.buttonEffect(ShiningLight.java:77) ~[?:?]
	at com.megacrit.cardcrawl.events.AbstractImageEvent.update(AbstractImageEvent.java:46) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.rooms.EventRoom.update(EventRoom.java:55) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2554) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by BDWSSBB** [comment]
Cause is the same as last bug report.
