### ISSUE TITLE
Unknown event causes crash

### ISSUE THREAD

**Issue by AvangionQ** [BDWSSBB/StS-Strawberry-Spire#9]
I click the ? mark and the game crashes ... no idea which event causes this fault.

Exception: java.lang.NullPointerException
16:47:12.669 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.actions.common.ApplyPowerAction.<init>(ApplyPowerAction.java:102) ~[?:?]
	at com.megacrit.cardcrawl.actions.common.ApplyPowerAction.<init>(ApplyPowerAction.java:127) ~[?:?]
	at StrawberrySpireMod.relics.ThornyGelberry.onAttacked(ThornyGelberry.java:30) ~[StrawberrySpire.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.damage(AbstractPlayer.java:1654) ~[?:?]
	at com.megacrit.cardcrawl.events.exordium.GoopPuddle.buttonEffect(GoopPuddle.java:67) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.events.AbstractImageEvent.update(AbstractImageEvent.java:46) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.rooms.EventRoom.update(EventRoom.java:55) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2554) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by BDWSSBB** [comment]
Cause is the same as last bug report.
